version: "3.1"

services:
  db:
    image: postgres
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      #- "./test_volume:/var/lib/postgresql/data"
      - test_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
volumes:
  test_volume:
    external: true

  #docker-compose -f ".\PostgreSQL\docker-compose.yml" up
  #docker run --name postgres -e POSTGRES_PASSWORD=postgres -v "test_volume:/var/lib/postgresql/data" -p 5432:5432 -d postgres  #To start with docker run